### ISSUE TITLE
More flexible filtering and sorting when not using semver

### ISSUE THREAD

**Issue by twk3** [dropseed/deps-git#2]
Given the following example:

```yaml
version: 3
dependencies:
- type: git
  settings:
    remotes:
      https://github.com/minio/mc.git:
        replace_in_files:
        - filename: charts/minio/values.yaml
          pattern: 'tag: "(\S+)"'
          semver: false
```

I see the following output, which is trying to replace the tag with the very first tag in the repo:

```sh
> Collecting with deps-git

> 1 new updates to be made
> [b2f436a] Update minio/mc from RELEASE.2018-07-13T00-53-22Z to RELEASE.Wed-Jun-24-21-56-09-GMT-2015
```

There appears to be some sorting still going on. And changing the pattern to be more specific doesn't seem to change the result at all?

```yaml
tag_prefix: 'RELEASE.'
pattern: 'tag: "RELEASE.(\d\d\d\d-\d\d-\d\dT\d\d-\d\d-\d\dZ)"'
```

**Comment by davegaeddert** [comment]
So without semver it just uses the order from `git ls-remote --tags` (which I believe is alphabetical by default). In this case:

```sh
❯ git ls-remote --sort version:refname --tags https://github.com/minio/mc.git
10d6e1860031262f0ee2968a6d0d316e453bf53e	refs/tags/OFFICIAL.2015-11-30T21-10-48Z
0fd1e3c387c0ae00772ff92572cad8a9c6fe16c2	refs/tags/OFFICIAL.2015-12-01T02-45-44Z
9fed1d73eed07adf4406b5bc7cbdac58243a4629	refs/tags/OFFICIAL.2015-12-06T01-57-42Z
7ee79bc960f80687ae111c81b486b4c2112fafba	refs/tags/OFFICIAL.2016-01-07T19-33-00Z
fbe47686583551290c54f94a538e01463ec9b470	refs/tags/OFFICIAL.2016-02-08T02-14-28Z
54761b22fdcc4c85c15b82904bb5670c80a5b800	refs/tags/RELEASE.2016-02-19T04-11-55Z
e7f4b6321201ddbf69b6f9dd13f280dd9f9335fd	refs/tags/RELEASE.2016-04-01T00-22-11Z
475670de7d9b10f4bc0d5d6f25f1a858c32c5628	refs/tags/RELEASE.2016-06-03T18-48-37Z
589c821f9bbeb30aaf6006d56e5e1965fa806b23	refs/tags/RELEASE.2016-07-13T21-46-05Z
947450089541c94a210f2479b0dbe12eced8349f	refs/tags/RELEASE.2016-08-18T01-41-03Z
a30f0aca850f8d637415efa83398dbf0d2b2cbb0	refs/tags/RELEASE.2016-08-18T01-41-03Z^{}
(... a bunch more)
ddbb4d9e40142a441aff51015742a509e09f12e5	refs/tags/RELEASE.2019-09-11T20-17-47Z
54ee3a280031adabc49a8309b74e5786cf266706	refs/tags/RELEASE.2019-09-11T20-17-47Z^{}
f635e3426329c2fa557927e9bd7b29c38b32b7d7	refs/tags/RELEASE.2019-09-20T00-09-55Z
57a9c6fab2064c30a036c1ff7f044f0be483cd8d	refs/tags/RELEASE.2019-09-20T00-09-55Z^{}
6ac5a0b51f9ea6ba2ca6cb6b83c9a16866c703c8	refs/tags/RELEASE.2019-09-24T01-36-20Z
643835013047aa27ed35de0ac5a4ab9538f0cd68	refs/tags/RELEASE.2019-09-24T01-36-20Z^{}
d750398f4d3413f9b6560616039179c92650b89e	refs/tags/RELEASE.Mon-05-Oct-2015-17-52-35-GMT
feebfa8154e5df55ea812f96dcf9c1c5bc4481cd	refs/tags/RELEASE.Sat-Sep-05-22-02-22-GMT-2015
ab4b66db0218749fcec6c158a24a9160cbf54da5	refs/tags/RELEASE.Sat-Sep-05-23-43-46-GMT-2015
45faafa49138c8f270e50fa81e6486665e664f06	refs/tags/RELEASE.Tue-Sep-22-04-02-16-GMT-2015
58de53db94d66ec668477531ae7132605d6c242e	refs/tags/RELEASE.Wed-Aug-26-19-58-04-GMT-2015
6e460703daa7ecc328a8bb6571208c7659906d1d	refs/tags/RELEASE.Wed-Jun-17-02-33-42-GMT-2015
3ee1b6b4a8178c40459a21b592730ae9edc8efc0	refs/tags/RELEASE.Wed-Jun-17-02-33-42-GMT-2015^{}
40c520c47c4af582d4c89869bacb5e45d69263aa	refs/tags/RELEASE.Wed-Jun-24-21-56-09-GMT-2015
6dd02b8a361dce0317de28bb08817a54caed9396	refs/tags/RELEASE.Wed-Jun-24-21-56-09-GMT-2015^{}
```

So it looks like the issue with this repo is they've got those old tags from 2015 with a different naming scheme.

There is a `--sort` option for `git ls-remote`, but it looks like we can't use any of the date fields without fetching/cloning the repo at some level, which I'd like to avoid?

The other idea that comes to mind initially is to change `tag_prefix` to a regular expression, where you could use a capture group to keep the part of the tag you wanted.

```yaml
filter: "RELEASE.(\d\d\d\d-\d\d-\d\dT\d\d-\d\d-\d\dZ)"
```

That route might help deal with other potential edge cases?

I will give it some thought (happy to hear feedback too) but in the meantime I think the workaround for this particular scenario would be to add `20` to your prefix. I think that should work, and will continue to work for the next 80 years or so 😉.
```yaml
tag_prefix: 'RELEASE.20'
pattern: 'tag: "RELEASE.20(\d\d-\d\d-\d\dT\d\d-\d\d-\d\dZ)"'
```

If you have other examples of a problem like this, let me know. If this is the only case, I might be tempted to just have you use the workaround for a little bit before pulling the trigger on a bigger change.

**Comment by twk3** [comment]
I like the idea of having tag_prefix being a regular expression. But in the meantime I will continue testing with the workaround.

**Comment by twk3** [comment]
Have been running into this more in my testing. Having the tag_prefix be a filter would be helpful.

I've got versions that look like:

- `curl-7_59_0` - https://github.com/curl/curl
- `release-2.1.8-stable` - https://github.com/libevent/libevent
- `release-57-1` - https://github.com/unicode-org/icu
- `OpenSSL_1_0_2o` - https://github.com/openssl/openssl.git

**Comment by davegaeddert** [comment]
Ok, I can take another look at this. Can you send me a link to the config where you're seeing this right now?

**Comment by twk3** [comment]
Yep, I have them commented out here: https://gitlab.com/gitlab-org/omnibus-gitlab/blob/2ddb828ce4a8362600c7f380f0f8e50669ba3e57/deps.yml#L172

**Comment by davegaeddert** [comment]
@twk3 do you want to take a look at this real quick and see if it makes sense (the examples anyway, you don't have to look at the code 😉)? 

PR https://github.com/dropseed/deps-git/pull/6

I haven't fully wrapped my head around it yet, but it seems like there may still be a sorting question here in your examples. Like on curl where they are using `_` as the semver separator...

**Comment by twk3** [comment]
The example looks good.

I do agree there will still be sorting issues, but that problem exists for tag_prefix, and anything non-semver atm.

As a separate request, if there was some way we could provide a conversion pattern for turning non-semver versions into semver just for sorting, that might help solve the problem?

**Comment by davegaeddert** [comment]
Agreed. So I was thinking the same on the conversion pattern, and now I'm wondering if this work should actually be combined instead of separated. @twk3 what do you think about something more like this?

```yaml
https://github.com/curl/curl.git:
  replace_in_files:
  - filename: file.txt
    pattern: curl==(\S+)

    tag_filter:
      from: 'curl-(\d+)_(\d+)_(\d+)'
      to: '$1'  # the original full tag name, this would be the default and what is used when doing replacement, PR titles, etc.
      sort_as: '$2.$3.$4'  # this format will only be used for sorting (semver)
```

I haven't actually tried that yet, so implementation might differ a little bit, but I'm wondering if that will tackle both issues at once.

**Comment by twk3** [comment]
It looks like it would to me. I think that would resolve most (maybe all), of our dependencies.

With that, even tags that just give us something like a timestamp could just be put into the sort_as with `0.0.$2` So even though they don't have built in support, we should be able to get okay sorting for anything integer based.

**Comment by davegaeddert** [comment]
Ok I went ahead and merged it. It changed slightly from the example I gave you:
```yaml
https://github.com/curl/curl.git:
  replace_in_files:
  - filename: file.txt
    pattern: curl==(\S+)

    tag_filter:
      matching: 'curl-(\d+)_(\d+)_(\d+)'

      # the original full tag name, this would be the default and what is used when doing replacement, PR titles, etc.
      # output_as: '$0'  # default value

      # this format will only be used for sorting (semver)
      sort_as: '$1.$2.$3' 
```

I expect some of the settings names/types to get cleaned up when this component goes 1.0, but by then we should have proper versioning of components and automatic PRs to update those and help point out any breaking changes in the deps config itself.

Let me know how it goes!
