### ISSUE TITLE
Sorting semver-ish tags

### ISSUE THREAD

**Issue by davegaeddert** [dropseed/deps-git#7]
The semver parsing is strict, and tags that are _almost_ semver can be out of order.

Examples:
- `curl-7_59_0` - https://github.com/curl/curl
- `release-57-1` - https://github.com/unicode-org/icu
- `OpenSSL_1_0_2o` - https://github.com/openssl/openssl.git

We want to be able to sort these kinds of tags in their semver order.

This settings API is evolving a little bit... here is one idea for how we could give some control over how tags are sorted and what string you actually end up using when doing the replacement in a file:

```yaml
https://github.com/curl/curl.git:
  replace_in_files:
  - filename: file.txt
    pattern: curl==(\S+)

    tag_filter:
      from: 'curl-(\d+)_(\d+)_(\d+)'
      to: '$1'  # the original full tag name
      sort_as: '$2.$3.$4'  # this format will only be used for sorting (semver)

    semver:
      enabled: true
      range: '< 8.0.0'
      prereleases: false
```
